package es.udc.fic.corpuslab.modules.notification.enums;

public enum NotificationType {
    RESEARCH_GROUP_INVITATION_RECEIVED,
    RESEARCH_GROUP_INVITATION_ACCEPTED,
    PROJECT_PARTICIPANT_ASSIGNED,
    PROJECT_ANNOTATION_COMPLETED,
    ANNOTATION_WARNING_MARKED
}
